<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-1TEHGD1" failures="1" tests="2" name="TestSmoke" time="9.009" errors="0" timestamp="2024-11-01T19:53:19 IST">
  <testcase classname="org.test.components.LoginTest" name="loginTC01" time="3.852"/>
  <testcase classname="org.test.components.LoginTest" name="signUpTc01" time="3.195">
    <failure type="java.lang.AssertionError" message="expected [Sign up successful.] but found [This user already exist.]">
      <![CDATA[java.lang.AssertionError: expected [Sign up successful.] but found [This user already exist.]
at org.pages.SignUpPage.signupFn(SignUpPage.java:53)
at org.test.components.LoginTest.signUpTc01(LoginTest.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- signUpTc01 -->
  <testcase classname="org.test.components.LoginTest" name="loginTC02" time="0.0">
    <ignored/>
  </testcase> <!-- loginTC02 -->
</testsuite> <!-- TestSmoke -->
